from stable_baselines3 import PPO
from AdversarialEnvironment import InstantNGPEnv
from NeRF import NeRF_Model
from helper import generate_transforms, baseline_classification

import ClipClassifier
import requests
import json
import copy
import numpy as np
import argparse
from PIL import Image
import os
import pandas as pd

def main(args):
    pretrained_model = ClipClassifier.CLIP_Classifier(args.clip_device)

    # Download the ImageNet labels file
    url = "https://raw.githubusercontent.com/anishathalye/imagenet-simple-labels/master/imagenet-simple-labels.json"
    response = requests.get(url)
    labels = response.json()

    baseline_classification(pretrained_model, args.input_image_folder, labels, args.target_class, args.true_class)
    generate_transforms(args.transforms_path, args.output_transforms_path, number_of_transforms=args.num_imgs)

    nerf_model = NeRF_Model(args.input_saved_nerf_file_path, args.output_saved_nerf_file_path, args.input_image_folder, args.output_transforms_path, args.output_image_folder)

    # Create environment instance
    env = InstantNGPEnv(pretrained_model, nerf_model, args, labels)

    # Create RL agent
    model = PPO('MlpPolicy', env, device='cpu', n_steps=args.n_steps, batch_size=args.batch_size, max_grad_norm = args.max_grad_norm)
    # Train the agent
    # Evaluate the trained agent
    episode_reward = 0
    obs, info = env.reset()
    _states = None

    while True:
        model.learn(total_timesteps=1)
        _, _states = model.predict(obs, _states)

        nerf_model.render_outputs(args.output_saved_nerf_file_path, args.output_transforms_path, args.output_image_folder, width=args.image_width, height=args.image_height)

        _, _, _, reward, info = env.pred_labels()

        episode_reward += reward
        print("Current episode reward: " + str(episode_reward))

        if (info['Target'] == info['Predicted'] and info['Confidence'] >= .65 and info["Num_Imgs"] >= 15):
            print("Episode reward:", episode_reward)
            break

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Reinforcement learning approach for generating adversarial noise.")
    parser.add_argument("--clip_device", default="cuda:0", type=str, help="Which device to execute clip on.")

    parser.add_argument("--input_image_folder", default="../BananaScene/Output/", type=str, help="Path to the images we will use to generate a 3D model using NeRF.")
    parser.add_argument("--output_image_folder", default="../BananaScene/AdvOut/", type=str, help="Folder to output generated images to.")
    parser.add_argument("--adversarial_noise_output_folder", default="./", type=str, help="Directory to store out adversarial noise generated by the agent.")
    parser.add_argument("--image_width", default=800, type=int, help="Width of rendered image from NeRF.")
    parser.add_argument("--image_height", default=800, type=int, help="Width of rendered image from NeRF.")
    parser.add_argument("--adversarial_noise_resize", default=200, type=int, help="This argument is used to determine the size of our adversarial noise when we paste it on our background image to test and see how it performs.")
    parser.add_argument("--save_adv_size", default=1080, type=int, help="The size we will save our adversarial noise image in. Currently gets saved as a square, will modify to save as other ratio.")

    parser.add_argument("--transforms_path", default="../BananaScene/transforms.json", type=str, help="Path to the original JSON path")
    parser.add_argument("--output_transforms_path", default="../BananaScene/short_transforms.json", type=str, help="Output path we will store the modified transforms file.")
    parser.add_argument("--input_saved_nerf_file_path", default="../SavedModel.msgpack", type=str, help="Path to our input saved NeRF model file.")
    parser.add_argument("--output_saved_nerf_file_path", default="../TestBanana.msgpack", type=str, help="Path to where we will save our generated NeRF model file.")

    parser.add_argument("--true_class", default="banana", type=str, help="True class of the object.")
    parser.add_argument("--target_class", default="slug", type=str, help="Target class to produce adversarial noise to target.")
    parser.add_argument('-l','--negative_labels', nargs='+', help='List of class labels to tell the agent to avoid predicting.')
    parser.add_argument("--num_imgs", default=20, type=int, help="Number of images to use as observation space for reinforcement learning.")

    # Hyperparameters
    parser.add_argument("--n_steps", default=32, type=int, help="Number of steps reinforcement agent can take.")
    parser.add_argument("--batch_size", default=32, type=int, help="Reinforcement learning batch size.")
    parser.add_argument("--max_grad_norm", default=.00001, type=float, help="Reinforcement maximum gradient norm. NOTE: If value is set too high, it may result in gradient explosion.")
    parser.add_argument('--theta_0', default= 100, type=int, help='Weight for target confidence in reward equation.')
    parser.add_argument("--theta_1", default=-1, type=int, help="Weight for true confidence in reward equation.")
    parser.add_argument("--theta_2", default=-0.00005, type=float, help="Weight for MSE influence in reward equation.")

    main(parser)